In [1]:
import numpy as np

## Task 1

In [2]:
A = np.array([[-24, -56, 51, -78], [-75, 26, 12, 60], [6, 2, -78, -48]])

In [3]:
AtA = A.T @ A
AtA

array([[ 6237,  -594, -2592, -2916],
       [ -594,  3816, -2700,  5832],
       [-2592, -2700,  8829,   486],
       [-2916,  5832,   486, 11988]])

Singular values

In [4]:
sigmas = np.sqrt(np.round(np.linalg.eigvals(AtA), 2))
sigmas

array([126., 105.,  63.,  -0.])

Normed eigenvectors

In [5]:
eigvecs = np.linalg.eig(AtA)[1]
np.round(eigvecs , 10)

array([[-0.28571429,  0.42857143,  0.85714286, -0.        ],
       [ 0.42857143,  0.28571429,  0.        , -0.85714286],
       [ 0.        , -0.85714286,  0.42857143, -0.28571429],
       [ 0.85714286, -0.        ,  0.28571429,  0.42857143]])

In [6]:
V = eigvecs
S = np.array([[126, 0, 0, 0], [0, 105, 0, 0], [0, 0, 63, 0]])
U = A @ V @ np.linalg.pinv(S)

In [7]:
U @ S @ V.T

array([[-24., -56.,  51., -78.],
       [-75.,  26.,  12.,  60.],
       [  6.,   2., -78., -48.]])

Truncated matrices 

In [8]:
U_2 = U[:, :2]
V_2 = V[:, :2]
S_2 = S[:2, :2]

Approximation

In [9]:
A_2 = U_2 @ S_2 @ V_2.T
A_2

array([[ -6., -56.,  60., -72.],
       [-39.,  26.,  30.,  72.],
       [ 42.,   2., -60., -36.]])

$\|A-A_2\|_2$

In [10]:
D = A - A_2
ev = np.linalg.eig(D.T @ D)[0]

np.sqrt(np.max(ev))

63.0

## Task 2

In [11]:
A = np.array([[-3.1, 0.19], [-4.09, -7.04]])
b = np.array([-2.97, -10.97])

A_hat = np.array([[-3, 0], [-4, -7]])
A_hat_inv = np.linalg.inv(A_hat)
b_hat = np.array([-3, -11])

delta_A = A_hat - A
delta_b = b_hat - b

In [12]:
A_hat.T @ A_hat

array([[25, 28],
       [28, 49]])

In [13]:
A_hat_inv.T @ A_hat_inv

array([[ 0.14739229, -0.02721088],
       [-0.02721088,  0.02040816]])

In [14]:
delta_A.T @ delta_A

array([[ 0.0181, -0.0154],
       [-0.0154,  0.0377]])

## Task 3

In [15]:
A_hat = np.array([[16, -9], [-2, -2]])
A_hat_inv = np.linalg.inv(A_hat)
b_hat = np.array([1, 4])

delta_A = np.array([[0.1, 0.15], [0, 0.05]])
delta_b = np.array([0.05,0.05])

Approximate solution

In [16]:
A_hat_inv @ b_hat

array([-0.68, -1.32])

In [17]:
A_hat.T @ A_hat

array([[ 260, -140],
       [-140,   85]])

In [18]:
A_hat_inv.T @ A_hat_inv

array([[0.0032, 0.0056],
       [0.0056, 0.1348]])

In [19]:
delta_A.T @ delta_A

array([[0.01 , 0.015],
       [0.015, 0.025]])

## Task 4

In [20]:
A_hat = np.array([[-5, -9], [2, -2]])

In [21]:
A_hat_inv = np.linalg.inv(A_hat)
A_hat_inv 

array([[-0.07142857,  0.32142857],
       [-0.07142857, -0.17857143]])

## Task 5

In [22]:
A = np.array([[21, 1, 1], [9, 25, 7], [3, 5, 21]])
b = np.array([3, 6, 6])

I = np.eye(3)
C = np.diag(np.diag(A))

In [23]:
P = (I - np.linalg.inv(C) @ A)
b_ = np.linalg.inv(C) @ b

In [24]:
np.round(P, 2)

array([[ 0.  , -0.05, -0.05],
       [-0.36,  0.  , -0.28],
       [-0.14, -0.24,  0.  ]])

In [25]:
p_norm = np.linalg.norm(P, 1)
b_norm = np.linalg.norm(b_, 1)
eps = 0.01

k = np.emath.logn(p_norm, (1 - p_norm) * eps / b_norm)
k

7.129888712186601

In [26]:
x_0 = np.array([0, 0, 0])

x = x_0

for i in range(8):
    x = P @ x + b_
    print(f'x_{i+1}', x)

x_1 [0.14285714 0.24       0.28571429]
x_2 [0.11782313 0.10857143 0.20816327]
x_3 [0.12777454 0.13929796 0.24303207]
x_4 [0.12465095 0.12595219 0.2342946 ]
x_5 [0.12570253 0.12952317 0.23791839]
x_6 [0.12535993 0.12812994 0.23691793]
x_7 [0.12547391 0.12853341 0.2372986 ]
x_8 [0.12543657 0.12838578 0.23718625]


## Task 6

In [27]:
A = np.array([[1, 1, 0, 0, 0], [1, 0, 0, 0, 1], [1, 1, 1, 1, 0], [1, 1, 0, 1, 1], [0, 0, 0, 1, 1]])

beta = 0.15
P = np.array([[1/4, 1/3, 0, 0, 0], [1/4, 0, 0, 0, 1/3], [1/4, 1/3, 1, 1/3, 0], 
              [1/4, 1/3, 0, 1/3, 1/3], [0, 0, 0, 1/3, 1/3]])
M = np.ones(shape=(5, 5)) / 5

Q = (1 - beta) * P + beta * M

In [28]:
Q

array([[0.2425    , 0.31333333, 0.03      , 0.03      , 0.03      ],
       [0.2425    , 0.03      , 0.03      , 0.03      , 0.31333333],
       [0.2425    , 0.31333333, 0.88      , 0.31333333, 0.03      ],
       [0.2425    , 0.31333333, 0.03      , 0.31333333, 0.31333333],
       [0.03      , 0.03      , 0.03      , 0.31333333, 0.31333333]])

In [29]:
x_0 = np.array([1/5, 1/5, 1/5, 1/5, 1/5])
x = x_0

for i in range(50):
    x = Q @ x
    print(f'Iteration {i+1}: x =', np.round(x, 3))

Iteration 1: x = [0.129 0.129 0.356 0.243 0.143]
Iteration 2: x = [0.094 0.098 0.465 0.203 0.139]
Iteration 3: x = [0.078 0.089 0.531 0.175 0.127]
Iteration 4: x = [0.072 0.083 0.573 0.157 0.116]
Iteration 5: x = [0.069 0.078 0.6   0.146 0.107]
Iteration 6: x = [0.067 0.075 0.618 0.138 0.102]
Iteration 7: x = [0.065 0.073 0.63  0.133 0.098]
Iteration 8: x = [0.065 0.072 0.638 0.13  0.096]
Iteration 9: x = [0.064 0.071 0.643 0.128 0.094]
Iteration 10: x = [0.064 0.07  0.647 0.127 0.093]
Iteration 11: x = [0.063 0.07  0.649 0.126 0.092]
Iteration 12: x = [0.063 0.07  0.65  0.125 0.092]
Iteration 13: x = [0.063 0.069 0.651 0.125 0.091]
Iteration 14: x = [0.063 0.069 0.652 0.124 0.091]
Iteration 15: x = [0.063 0.069 0.653 0.124 0.091]
Iteration 16: x = [0.063 0.069 0.653 0.124 0.091]
Iteration 17: x = [0.063 0.069 0.653 0.124 0.091]
Iteration 18: x = [0.063 0.069 0.653 0.124 0.091]
Iteration 19: x = [0.063 0.069 0.653 0.124 0.091]
Iteration 20: x = [0.063 0.069 0.653 0.124 0.091]
Iteration

In [30]:
np.round(x, 3)

array([0.063, 0.069, 0.653, 0.124, 0.091])

In [31]:
np.linalg.norm(x, 1)

1.0000000000000007

## Task 7

In [32]:
A = np.array([[0, -1, 0], [17, 6, -4], [5, -1, -1]])
eigvals = np.linalg.eig(A)[0]
eigvec3, eigvec1 = np.array([1, -3, 2]), np.array([1, -1, 3])
np.round(eigvals, 2)

array([3., 1., 1.])

In [33]:
J = np.array([[3, 0, 0], [0, 1, 1], [0, 0, 1]])
J

array([[3, 0, 0],
       [0, 1, 1],
       [0, 0, 1]])

In [34]:
B = A - np.eye(3)
B

array([[-1., -1.,  0.],
       [17.,  5., -4.],
       [ 5., -1., -2.]])

In [35]:
eigvec12 = np.array([1/3, -4/3, 0])

In [36]:
P = np.array([eigvec3, eigvec1, eigvec12]).T
P1 = np.linalg.inv(P)
P1

array([[-4.        , -1.        ,  1.        ],
       [ 2.66666667,  0.66666667, -0.33333333],
       [ 7.        ,  1.        , -2.        ]])

In [37]:
f_J = np.array([[np.exp(4), 0, 0], [0, np.exp(2), np.exp(2)], [0, 0, np.exp(2)]])
f_J

array([[54.59815003,  0.        ,  0.        ],
       [ 0.        ,  7.3890561 ,  7.3890561 ],
       [ 0.        ,  0.        ,  7.3890561 ]])

In [38]:
f_A = P @ f_J @ P1
np.round(f_A, 2)

array([[-129.72,  -39.82,   32.43],
       [ 514.79,  141.63, -126.85],
       [-222.5 ,  -72.25,   57.47]])